api_platform:
    title: 'Recipes API'
    description: 'Beautiful delicious recipes !'
    version: 1.0.0
    show_webby: false

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header

    #formats:
    #    jsonld: ['application/ld+json']
    #docs_formats:
    #    jsonld: ['application/ld+json']
    #    jsonopenapi: ['application/vnd.openapi+json']
    #    html: ['text/html']
    #defaults:
    #    stateless: true
    #    cache_headers:
    #        vary: ['Content-Type', 'Authorization', 'Origin']
    #    extra_properties:
    #        standard_put: true
    #        rfc_7807_compliant_errors: true
    #event_listeners_backward_compatibility_layer: false
    #keep_legacy_inflector: false
