twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        # Setting
        setting: '@App\Service\SettingService'

        # Language
        locales: "%app_locales%"

        # Google
        google_maps_api_key: "%google_maps_api_key%"

        # Date and time
        date_format: "%date_format%"
        date_format_date_only: "%date_format_date_only%"
        date_timezone: "%date_timezone%"

    date:
        format: "%date_format%"
        timezone: "%date_timezone%"

when@test:
    twig:
        strict_variables: true
