version: '3.7'

services:

###> doctrine/doctrine-bundle ###
    database:
        ports:
            - "6432:3306"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
    mailer:
        image: schickling/mailcatcher
        ports: ["1025", "1080"]
###< symfony/mailer ###
