version: '3.7'

services:

###> doctrine/doctrine-bundle ###
    database:
        image: 'mysql:latest'
        environment:
            # You should definitely change the password in production
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-marmiton}

    #database:
        #image: 'mariadb:latest'
        #environment:
            # You should definitely change the password in production
            #MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-!ChangeMe!}
            #MARIADB_DATABASE: ${MARIADB_DATABASE:-marmiton}
        #volumes:
            #- database_data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

###> phpmyadmin/phpmyadmin ###
    phpmyadmin:
        image: 'phpmyadmin:latest'
        restart: always
        depends_on:
            - database
        ports:
            - 8080:80
        environment:
            PMA_HOST: database
        #networks:
            #- dev
###< phpmyadmin/phpmyadmin ###

volumes:
###> doctrine/doctrine-bundle ###
    database_data:
###< doctrine/doctrine-bundle ###
