version: '3.7'

services:

###> doctrine/doctrine-bundle ###
    database:
        ports:
            - "3306:3306"
###< doctrine/doctrine-bundle ###

###> phpmyadmin/phpmyadmin ###
    phpmyadmin:
        ports:
            - "8080:80"
###< phpmyadmin/phpmyadmin ###

###> symfony/mailer ###
    mailer:
        image: schickling/mailcatcher
        ports: ["1025", "1080"]
###< symfony/mailer ###
